### ISSUE TITLE
why choose the Nativescript and angular not the react ?

### ISSUE THREAD

**Issue by wade-liwei** [alexander171294/web-poker#14] opened 2019-11-13 06:27 UTC

**Comment by alexander171294** [comment] 2019-11-13 09:12
Hello!,

First, start with the basis that JavaScript frameworks and libraries are limited by JavaScript, they can do the same, both jquery and angular, vue, react, backbone, etc. (AngularJS is out of analysis because it is deprecated, and is prety bad hehe)

At this point, I analized the simplest to do basics things as routing, lazy load compose (SPA), interpolation, etc. In this aspect the three frameworks are similar and the discusion is limited to these, removing of the selection to javascript vanilla, jquery, etc because are more complex (in code) to do the simple tasks.

Then I analyzed the performance, and with minimal diferences are the three similars.

I taked in consideration then, the maintainance, in this case Angular is in top of the three because brings by default typescript. Typescript add clarity and definition to the objects in parameters, etc. 
Additionally the structure of Angular give more order and ease of deducing/analyzing the code.

I checked another things then I decided by Angular in web development.

Now to do mobile, its more simple because, first I discarded full native in order to prevent code double in two languages, and maintain double.
Of the hybrid frameworks, I discarded react because I trying to preserve the consistence of the project using the same framework and format in all of the frontends. This decision leave me with two reasonable options, Ionic and Nativescript.

**Comment by wade-liwei** [comment] 2019-11-13 12:43
I am very glad see your reply.
I am a back end engineer, and an English beginner.
So can not provide any opinion on the front end, I just think react is simple.

I want to write a blockchain poker game(the server game logic on the blockchain), I am looking for mobile poker game.

Hope we can work together.

**Comment by alexander171294** [comment] 2019-11-13 13:04
Hey, grat idea.

Just now, we has designed the backend architecture in java, you can see the protocol here:

https://github.com/alexander171294/web-poker/wiki

and the backend here:
https://github.com/alexander171294/web-poker/tree/master/backend

But if i can help you in any way, please let me know.

Alexander Eberle.

**Comment by wade-liwei** [comment] 2019-11-13 13:22
Do you consider mental poker protocol ?

**Comment by wade-liwei** [comment] 2019-11-13 13:23
Do you consider using the mental poker protocol ?

Do you a telegram account ?

**Comment by wade-liwei** [comment] 2019-11-13 13:39
I want to use your front end codes.

Wade Li

**Comment by wade-liwei** [comment] 2019-11-13 15:40
Could you write a document about how to deploy the backend game server ?

or provide a test backend server address ??
and tell me how to connect the different backend server in the frontend.

**Comment by alexander171294** [comment] 2019-11-13 17:14
Hi!, about mental poker protocol we doesn't consider (our protocol is defined in RFC corresponding).

About use our frontend, no problem!, use what you want or need, this is an open source project.

About backend game server, actually the server is in a pre-alpha status, we suppose that release first alpha version around 500th or 550th commit.

All of the servers and the client are released with the respective Docker images and instructions for run and register tables, configure, etc. and to deploy in kubernetes cluster.

If you want to start development environment, you need to import backend folder content in your eclipse as maven project for example, and run ApiClient main class, Orchestrator, and finally RoomServer, this projects:

Api Client:
https://github.com/alexander171294/web-poker/blob/master/backend/ApiServer/src/main/java/ar/com/tandilweb/ApiServer/ApiServer.java

Orchestrator:
https://github.com/alexander171294/web-poker/blob/master/backend/orchestrator/src/main/java/ar/com/tandilweb/orchestrator/OrchestratorServer.java

Room Server:
https://github.com/alexander171294/web-poker/blob/master/backend/room/src/main/java/ar/com/tandilweb/room/RoomServer.java

Finally Orchestrator and Api Client share the persitence (MySQL database) configured the demo/test here:

https://github.com/alexander171294/web-poker/blob/master/backend/ApiServer/src/main/resources/database.properties

As is defined in diagram of exchange protocol here:
https://docs.google.com/document/d/1gBXpZ4h8RLj_pJVv9hG6ApM5y0AJc0k10xR1c9yYKWg/edit
spanish outdated version: 
https://docs.google.com/document/d/1l1gP2jEycPqCoYrP-loGGLYfkEbfKFVbOzOFcYMtkMU/edit

And texas hold'em protocol is defined here:
https://docs.google.com/document/d/1ULFXVKCAf2QbRVwc1_-9_eszVPTBcrsdwjivCzlm6VY/edit

**Closed by alexander171294** 2019-11-13 17:14 UTC
